version: '3'
services: 
  app:
    build: ./app/
    container_name: pleasanter-app
    volumes: 
      - ./app/Rds.json:/web/pleasanter/Implem.Pleasanter/App_Data/Parameters/Rds.json
      - ./app/pleasanter.sh:/home/Pleasanter.NetCore/cmdnetcore/pleasanter.sh
      - ./app/supervisord.conf:/usr/local/etc/supervisord.conf
    ports:
      - 80:80
    networks: 
      - pleasanter-network
    depends_on: 
      - db
  db:
    build: ./db/
    container_name: pleasanter-db
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
    networks:
      - pleasanter-network

networks:
  pleasanter-network:
    driver: bridge

    